### PR TITLE
Improve ReadMe documentation

### PR DESCRIPTION
**Pull request by dkhmelenko**
I personally struggled a bit with the default values for properties. I hope this can help somebody.

### CODE REVIEW

**Comment by bobvanderlinden** [comment]
The default value for `blockingLabels` should already be empty. Your initial configuration can just not mention `blockingLabels` at all. Should I maybe just remove the `blockingLabels` entry from the example configuration? Or add it as a comment?

**Comment by dkhmelenko** [comment]
I would prefer to mention it in a comment. Maybe something like that
```
don't put `blockingLabels` if none blocking labels should be applied.
```

**Comment by bobvanderlinden** [comment]
I didn't like mentioning how to create an empty section to the configuration file, so I have added a small note for the sections that are affected that they need te be removed when not used. See #82. Let me know whether this would've resolved your issue.

**Comment by dkhmelenko** [comment]
Yes, it works for me. Thanks!

**Pull request closed without merging**
