### PR TITLE
Show a Better Status Message if PR is Closed

### LINKED ISSUE #823: If the PR status is 'merged', it shouldn't keep checking
I keep seeing this state, where the PR gets merged and the `auto-merge` is triggered and updates the check status to 'not merging':

image

I think it should keep showing the last bot status before the merge took place. Ideally, if the bot merged the PR, that status could display something along the lines "probot-auto-merge bot successfully merged this pull request" and update the check status to a green check ✅ 

At the moment this isn't a functional bug, but rather an annoying status. If I made the `auto-merge` check a mandatory check in my repository settings, all PRs wouldn't be green cuz the status updates to that "gray" state, which's weird cuz everything went fine

### PR DESCRIPTION
**Pull request by rogerluan**
## Description

Resolves #823 

### It will show '✅ Merged'  when the PR has already been merged

image

### It will show '✅ Closed' if the PR is closed without being merged.

image

### CODE REVIEW

**Comment by bobvanderlinden** [comment]
Thanks a lot for the PR. I had a few suggestions that I made in the following branch: https://github.com/bobvanderlinden/probot-auto-merge/tree/probot-auto-merge/better-status-message

Other than that, this looks good. I'm considering using `success` conclusion for all auto-merge states, but that can be discussed/implemented in a separate PR.

**Comment by rogerluan** [comment]
Your changes look great @bobvanderlinden, specially `type CheckOptions = Omit<ChecksCreateParams, 'head_sha'>` 😄

**Comment by bobvanderlinden** [comment]
Could you pull in my changes? I do not have rights in git to change your branch it seems ;) (`git pull https://github.com/bobvanderlinden/probot-auto-merge probot-auto-merge/better-status-message`)

**Comment by rogerluan** [comment]
Done @bobvanderlinden 😁 

The reason you don't have write access to my branch is cuz it's owned by an organization rather than an individual account 😬 it's a GitHub limitation. PRs opened by personal accounts can choose to "allow maintainers to write", but companies can't 😞

**Review by bobvanderlinden — APPROVED** [review]
This looks good 👍 Thanks for the PR!

**Comment by bobvanderlinden** [comment]
Ah, no rights to bring the branch up-to-date. Could you do that?

**Comment by rogerluan** [comment]
@bobvanderlinden done :)

**Comment by bobvanderlinden** [comment]
auto-merge is having a hard time. That merge took more than an hour :/

**Pull request merged**
